apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: deployment-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-test
  template:
    metadata:
      labels:
        app: deployment-test
    spec:
      containers:
      - name: deployment-test
        image: debian:jessie
        command: ["/bin/sh"]
        args: ['-c', 'while true; do echo "Hello, ${USERNAME}!"; sleep 10; done']
        env:
        - name: USERNAME
          value: Sergey
          