apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: myproxy
  labels:
    run: myproxy
  name: myproxy
spec:
  selector:
    matchLabels:
      run: myproxy
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        run: myproxy
    spec:
      containers:
      - image: nginx:1.13
        name: myproxy
        ports:
          - containerPort: 8080
            hostPort: 81
      tolerations:
      - effect: NoSchedule
        operator: Exists